config:
  learning_rate: 0.2
  noise_std_dev: 0.4
  n_populations: 1000
  n_individuals: 2
  n_timesteps_per_trajectory: 20

  environment: "Maze"
  model: "FeedForwardNeuralNetwork"
  reward: "binary"
  hidden_layer_activation: "selu"
  output_activation: "none"

  n_hidden_layers: 1
  n_nodes_per_layer: 10
  input_size: 9
  output_size: 4