config:
  learning_rate: 0.04
  noise_std_dev: 0.4
  n_populations: 1000
  n_individuals: 20
  n_timesteps_per_trajectory: 7

  environment: "Maze"
  model: "FeedForwardNeuralNetwork"
  reward: "manhattan_distance"

  n_hidden_layers: 1
  n_nodes_per_layer: 10
  input_size: 8
  output_size: 4