default_config:
  learning_rate: 0.1
  noise_std_dev: 0.04
  n_populations: 10
  n_individuals: 10
  n_timesteps_per_trajectory: 10
  environment: "Maze"
  model: "FeedForwardNeuralNetwork"
  reward: "manhattan_distance"
  n_hidden_layers: 1
  n_nodes_per_layer: 10
  input_size: 8
  output_size: 4