default_config:
  learning_rate: 0.2
  noise_std_dev: 0.8
  n_populations: 500
  n_individuals: 5
  n_timesteps_per_trajectory: 30

  environment: "Maze"
  environment_index: 1
  model: "FeedForwardNeuralNetwork"
  reward: "binary"
  hidden_layer_activation: "selu"
  output_activation: "none"

  n_hidden_layers: 1
  n_nodes_per_layer: 10
  input_size: 9
  output_size: 4